from dydx3.constants import API_HOST_GOERLI,API_HOST_MAINNET
from decouple import config 

#!!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"

#Close all open positions and orders
ABORT_ALL_POSITIONS = False

#Find cointegrated pairs
FIND_COINTEGRATED = True

#Place Trades
PLACE_TRADES = True

#Resolution
RESOLUTION = "1HOUR"

#Stats window
WINDOW = 21

#Tresholds
MAX_HALF_LIFE = 24
ZSCORE_TRESH = 1.5
USD_PER_TRADE = 10
USD_MIN_COLATERAL = 300

#Treshholds for closing
CLOSE_AT_ZSCORE_CROSS = True

#ETHEREUM ADRESS
ETHEREUM_ADRESS = "0x802818307b07ebCcD13C5ac726e85aD530a48cE6"

# WALLET PRIVATE KEY
ETH_PRIVATE_KEY = "0xa6b0675707af31f9998c8c74df0fa978f99fab0065a957f736d36e03e0af5685"

# KEYS - Production
# Must to be on Mainnet on DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - Development
# Must to be on Testnet on DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

#KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

#HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

#HTTP Provider
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/op8D13PoK2Ds-rg6fIccIXbO_eRfzZMo"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/h8Z_urvQDC9Oya08wMVWd0iUnFrr39f9"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET

